repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.3.4
    hooks:
      - id: sqlfluff-lint
        additional_dependencies: [
          'dbt-postgres==1.5.2',
          'sqlfluff-templater-dbt==2.3.4'
        ]
      - id: sqlfluff-fix
        stages: [manual]  # this command is available only to run manually
        additional_dependencies: [
          'dbt-postgres==1.5.2',
          'sqlfluff-templater-dbt==2.3.4'
        ]
