version: 2

sources:
  - name: aethervest
    schema: aethervest_src  
    tables:
      - name: products
      - name: product_listings
      - name: product_listings_history
      - name: retailers
      - name: stores
      - name: statcan_food_prices
  - name: static
    schema: public
    tables:
      - name: census_divisions
  - name: stahl
    schema: stahl
    tables:
      - name: dim_stores

