version: 2

sources:
  - name: aethervest
    schema: aethervest_src
    tables:
      - name: products
      - name: product_listings
      - name: product_listings_history
      - name: retailers
      - name: stores
      - name: statcan_food_prices
      - name: statcan_cpi_monthly
  - name: static
    schema: static
    tables:
      - name: statcan_census_divisions
